export { default as armChair } from "./../assets/icons/Rooms/Living Room/armChair.svg";
export { default as balcony } from "./../assets/icons/Rooms/Living Room/balcony.svg";
export { default as cabinet } from "./../assets/icons/Rooms/Living Room/cabinet.svg";
export { default as carpet } from "./../assets/icons/Rooms/Living Room/carpet.svg";
export { default as kettle } from "./../assets/icons/Rooms/Living Room/kettle.svg";
export { default as minibar } from "./../assets/icons/Rooms/Living Room/minibar.svg";
export { default as phone } from "./../assets/icons/Rooms/Living Room/phone.svg";
export { default as safe } from "./../assets/icons/Rooms/Living Room/safe.svg";
export { default as sofa } from "./../assets/icons/Rooms/Living Room/sofa.svg";
export { default as wardrobe } from "./../assets/icons/Rooms/Living Room/wardrobe.svg";
export { default as airCondition } from "./../assets/icons/About/airConditioning.svg";
export { default as wifi } from "./../assets/icons/About/wifi.svg";
export { default as teakit } from "./../assets/icons/Rooms/Living Room/tea.svg";
export { default as teakitBrown } from "./../assets/icons/Rooms/LivingRoomBrown/tea.svg";
export { default as tv } from "./../assets/icons/Rooms/Living Room/TV.svg";


export { default as bedBrown } from "./../assets/icons/Rooms/LivingRoomBrown/bed.svg";
export { default as carpetBrown } from "./../assets/icons/Rooms/LivingRoomBrown/carpet.svg";
export { default as safeBrown } from "./../assets/icons/Rooms/LivingRoomBrown/safe.svg";
export { default as kettleBrown } from "./../assets/icons/Rooms/LivingRoomBrown/kettle.svg";
export { default as conditionBrown } from "./../assets/icons/Rooms/LivingRoomBrown/condition.svg";
export { default as tvBrown } from "./../assets/icons/Rooms/LivingRoomBrown/tv.svg";
export { default as phoneBrown } from "./../assets/icons/Rooms/LivingRoomBrown/phone.svg";
export { default as wifiBrown } from "./../assets/icons/Rooms/LivingRoomBrown/wifi.svg";
export { default as balconyBrown } from "./../assets/icons/Rooms/LivingRoomBrown/balcony.svg";
export { default as sofaBrown } from "./../assets/icons/Rooms/LivingRoomBrown/sofa.svg";
export { default as wardrobeBrown } from "./../assets/icons/Rooms/LivingRoomBrown/wardrobe.svg";
export { default as cabinetBrown } from "./../assets/icons/Rooms/LivingRoomBrown/cabinet.svg";
export { default as bathRobe } from "./../assets/icons/Rooms/LivingRoomBrown/bathRobe.svg";
export { default as cosmetic } from "./../assets/icons/Rooms/LivingRoomBrown/cosmetic.svg";
export { default as minibarBrown } from "./../assets/icons/Rooms/LivingRoomBrown/minibar.svg";
export { default as hairDryer } from "./../assets/icons/Rooms/LivingRoomBrown/hairDryer.svg";
export { default as shovergigi } from "./../assets/icons/Rooms/LivingRoomBrown/shovergigi.svg";
export { default as shower } from "./../assets/icons/Rooms/LivingRoomBrown/shower.svg";
export { default as slippers } from "./../assets/icons/Rooms/LivingRoomBrown/slippers.svg";
export { default as towels } from "./../assets/icons/Rooms/LivingRoomBrown/towels.svg";
export { default as wc } from "./../assets/icons/Rooms/LivingRoomBrown/wc.svg";

export  { default as presenter} from "../assets/icons/ConferenceService/presenter.svg";
export  { default as projector} from "../assets/icons/ConferenceService/projector.svg";
export  { default as screen} from "../assets/icons/ConferenceService/screen.svg";  
export  { default as microphone} from "../assets/icons/ConferenceService/microphone.svg";
export  { default as notebook} from "../assets/icons/ConferenceService/notebook.svg";
export  { default as paper} from "../assets/icons/ConferenceService/paper.svg";
export  { default as soundSystem} from "../assets/icons/ConferenceService/soundsystem.svg";
export  { default as flipchart} from "../assets/icons/ConferenceService/flipchart.svg";

export  { default as door} from '../assets/icons/About/door.svg';
export  { default as restaurant} from '../assets/icons/About/restaurant.svg';
export  { default as karaoke} from '../assets/icons/About/karaoke.svg';
export  { default as terasse} from '../assets/icons/About/terrase.svg';
export  { default as conferenceRoom} from '../assets/icons/About/conferenceRoom.svg';
export  { default as wheelChair} from '../assets/icons/About/wheelchairuser.svg';
export  { default as parking} from '../assets/icons/About/parking.svg';
export  { default as pet} from '../assets/icons/About/pet.svg';

export  { default as reception} from '../assets/icons/About/reception.svg'; 
export  { default as roomService} from '../assets/icons/About/roomService.svg';
export  { default as car} from '../assets/icons/About/car.svg';
export  { default as breakfast} from '../assets/icons/Rooms/Living Room/cup.svg';
export  { default as ironingChlothes} from '../assets/icons/About/ironingChlothes.svg';
export  { default as washingMachine} from '../assets/icons/About/washingMachine.svg';
export  { default as guest} from '../assets/icons/Rooms/guests.svg';
export  { default as babybed} from '../assets/icons/Rooms/Living Room/babybed.svg';
export  { default as kid} from '../assets/icons/Rooms/Living Room/kid.svg';
export  { default as olderkid} from '../assets/icons/Rooms/Living Room/olderKid.svg';
export  { default as cup} from '../assets/icons/Rooms/Living Room/cup.svg';
export  { default as houseBrown} from '../assets/icons/Rooms/house.svg';
export  { default as squareBrown} from '../assets/icons/Rooms/squareBrown.svg';
export  { default as square} from '../assets/icons/Rooms/square.svg';
export  { default as house} from '../assets/icons/Rooms/house.svg';
export  { default as floor} from '../assets/icons/About/floor.svg';
export  { default as guestBrown} from '../assets/icons/Rooms/guestsBrown.svg';  
export  { default as navigate} from '../assets/icons/About/navigation.svg';
export  { default as instagram} from '../assets/icons/instagram-f-svgrepo-com.svg';
export  { default as visa} from '../assets/icons/visa.svg';
export  { default as mastercard} from '../assets/icons/mastercard.svg';
export  { default as rating} from '../assets/icons/rating.svg';
export  { default as squareWhite} from '../assets/icons/Rooms/squareWhite.svg';
export  { default as guestWhite} from '../assets/icons/Rooms/guestWhite.svg';
export  { default as list} from '../assets/icons/Modal/list.svg';
export  { default as calendar} from '../assets/icons/Modal/calendar.svg';
export  { default as guestAmmenties} from '../assets/icons/Rooms/guestAmmenties.svg';

export  { default as location} from '../assets/icons/Contacts/Location.svg';
export  { default as menu} from '../assets/icons/Menu.svg';
export {default as calendarBooking} from '../assets/icons/Calendar.svg';
export {default as callUs} from '../assets/icons/phone.svg';
